### PR TITLE
refactor protoparse, fixes multiple issues

### LINKED ISSUE #275: difference to protoc: tag number validation overly strict
The following .proto file fails parsing with protoreflect, but not with protoc:

```
syntax = "proto2";

message Foo {
  extend proto2.bridge.MessageSet {
    optional string message_set_extension = 999999999;
  }
}
```

I’m getting this error message from protoreflect:
```
msgsetrepro.proto:5:45: tag number 999999999 is higher than max allowed tag number (536870911)
```

I can’t find corresponding tag validation code in protoc itself, but this code seems related:

https://github.com/protocolbuffers/protobuf/blob/7f520092d9050d96fb4b707ad11a51701af4ce49/src/google/protobuf/compiler/parser.cc#L806

To me, it looks like for message sets, the maximum tag number is kint32max, not FieldDescriptor::kMaxNumber.

### PR DESCRIPTION
**Pull request by jhump**
* defers a lot of validation to after the AST is fully constructed
* in particular, defers tag validation to after message options are parsed in order to know if it has `message_set_wire_format option`, which impacts allowed tag range
* fixes issues with very large constant numbers (that overflow `uint64` or underflow `int64`)
* refactors grammar around option names and fixes issue where extensions on message options aren't parsed correctly
* fixes issues related to groups in oneofs
* fixes issues with reserved name validation
* adds some util methods to shrink the boiler-plate for error creation and error handling (`errorWithPos(...)`, `(*errorHandler) handleErrWithPos(...)`)
* breaks up monolithic `parser.go` into three files: `parser.go`, `validation.go`, and `descriptor_protos.go`
* adds numerous new validation test cases to catch various issues that were fixed

Fixes #275, #307, #308, #312, #313, #314, #315

### CODE REVIEW

File: desc/internal/util.go [hunk 1]
```diff
@@ -1,13 +1,18 @@
...
+	"math"
 	"unicode"
 	"unicode/utf8"
 )
 
 const (
-	// MaxTag is the maximum allowed tag number for a field.
-	MaxTag = 536870911 // 2^29 - 1
+	// MaxNormalTag is the maximum allowed tag number for a field in a normal message.
+	MaxNormalTag = 536870911 // 2^29 - 1
```
Comment (bufdev) [inline desc/internal/util.go:11]: Nit: I might switch this from MaxNormalTag/MaxTag to MaxTag/MaxTagMessageSetWireFormat since the message set max tag is the edge case, but more a matter of preference

Comment (jhump) [reply desc/internal/util.go:11]: I wanted a name like `MaxTag` to be the actual maximum value -- the greater of the two -- because I thought that would be more clear.

Maybe `MaxNormalTag`, `MaxMessageSetTag`, and `MaxTag = MaxMessageSetTag`?

Comment (bufdev) [reply desc/internal/util.go:11]: Yea that works! Or keep as is, either way :-)

File: desc/builder/field.go [hunk 2]
```diff
@@ -508,6 +508,11 @@ func (flb *FieldBuilder) buildProto(path []int32, sourceInfo *dpb.SourceCodeInfo
 		def = proto.String(flb.Default)
 	}
 
+	// normal (non-messageset) messages have lower tag limit, so enforce that here
+	if !isMessageSet && flb.number > internal.MaxNormalTag {
```
Comment (bufdev) [inline desc/builder/field.go:512]: Do you want to enforce the `isMessageSet` case as well here? I'm sure you've thought of this and there's likely a reason you're not, but just checking.

File: desc/protoparse/ast.go [hunk 3]
```diff
@@ -729,17 +761,46 @@ type extensionRangeNode struct {
 type rangeNode struct {
 	basicCompositeNode
 	stNode, enNode node
-	st, en         int32
+	enMax          bool
```
Comment (bufdev) [inline desc/protoparse/ast.go:764]: nit: `endMax`?

File: desc/protoparse/validate.go [hunk 4]
```diff
@@ -0,0 +1,347 @@
...
+import (
+	"fmt"
+	"sort"
+
+	"github.com/golang/protobuf/proto"
+
+	dpb "github.com/golang/protobuf/protoc-gen-go/descriptor"
+)
+
+func basicValidate(res *parseResult, containsErrors bool) {
```
Comment (bufdev) [inline desc/protoparse/validate.go:12]: nit: `validateBasic`?

File: desc/protoprint/print.go [hunk 5]
```diff
@@ -716,6 +716,10 @@ func (p *Printer) printMessageBody(md *desc.MessageDescriptor, mf *dynamic.Messa
 	}
 
 	skip := map[interface{}]bool{}
+	maxTag := int32(internal.MaxNormalTag)
```
Comment (bufdev) [inline desc/protoprint/print.go:719]: Super nit: You might want to turn this into a shared helper function `GetMaxTag(isMessageSet bool)` instead of having the public consts

File: desc/builder/field.go (hunk 2 above)
Comment (jhump) [reply desc/builder/field.go:512]: The code already validates that tags are never > `internal.MaxTag` when fields are created. This is a deferred check just for the tighter range imposed on non-messageset fields, which can't be performed until we know the field's context (e.g. is it part of a messageset or not).

File: desc/protoparse/ast.go (hunk 3 above)
Comment (jhump) [reply desc/protoparse/ast.go:764]: Yeah, I'm not sure why I used `st` and `en` instead of `start` and `end`. I can do a quick rename for this and the two fields above.

File: desc/protoparse/validate.go (hunk 4 above)
Comment (jhump) [reply desc/protoparse/validate.go:12]: Sure... this was already called this FWIW (just moved from `parser.go` into its own file.

File: desc/protoprint/print.go (hunk 5 above)
Comment (jhump) [reply desc/protoprint/print.go:719]: Yeah, that's a good idea.

File: desc/protoparse/validate.go (hunk 4 above)
Comment (bufdev) [reply desc/protoparse/validate.go:12]: Ah yea, I was going to add the caveat that this might already have been there - people commenting on something that was just moved around as part of a refactoring PRs is a pet peeve of mine, so feel free to ignore this :-)

File: desc/builder/field.go (hunk 2 above)
Comment (bufdev) [reply desc/builder/field.go:512]: Ah ok

File: desc/protoprint/print.go (hunk 5 above)
Comment (jhump) [reply desc/protoprint/print.go]: done

File: desc/protoparse/validate.go (hunk 4 above)
Comment (jhump) [reply desc/protoparse/validate.go]: renamed

File: desc/protoparse/ast.go (hunk 3 above)
Comment (jhump) [reply desc/protoparse/ast.go]: renamed

File: desc/builder/field.go (hunk 2 above)
Comment (jhump) [reply desc/builder/field.go]: I changed this to just use `internal.GetMaxTag` so it's simpler to follow along

File: desc/internal/util.go (hunk 1 above)
Comment (jhump) [reply desc/internal/util.go:11]: In addition to adding `GetMaxTag(messageSet bool)`, I also left these other constants, but tweaked them per discussion above.

**Comment by jhump** [comment]
Travis has been failing to report build status quite a lot lately :(

Build is good: https://travis-ci.org/github/jhump/protoreflect/builds/679896778

Here goes nothing'
