### PR TITLE
fix panic in protoparse

### LINKED ISSUE #139: panic: runtime error: invalid memory address or nil pointer dereference
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x6b75f5]

goroutine 1 [running]:
github.com/jhump/protoreflect/desc/protoparse.(*intLiteralNode).leadingComments(0x0, 0xc0004a7b80, 0x14, 0xc00044b1a0)
	<autogenerated>:1 +0x5
github.com/jhump/protoreflect/desc/protoparse.(*sourceCodeInfo).newLoc(0xc000073d30, 0x7f70c0, 0x0, 0xc000073c80, 0x5, 0xa)
	F:/GolangWorks/src/github.com/jhump/protoreflect/desc/protoparse/parser.go:1222 +0x53
github.com/jhump/protoreflect/desc/protoparse.(*parseResult).generateSourceCodeInfoForEnum(0xc0002a7920, 0xc000073d30, 0xc0000c0e00, 0xc000073c80, 0x2, 0xa)
	F:/GolangWorks/src/github.com/jhump/protoreflect/desc/protoparse/parser.go:1157 +0x5b0
github.com/jhump/protoreflect/desc/protoparse.(*parseResult).generateSourceCodeInfo(0xc0002a7920, 0xc00006f9e0)
	F:/GolangWorks/src/github.com/jhump/protoreflect/desc/protoparse/parser.go:933 +0x3ee
github.com/jhump/protoreflect/desc/protoparse.Parser.ParseFiles(0xc0001bfbf0, 0x1, 0x1, 0x0, 0x0, 0x1, 0xc0000c0b80, 0x8, 0x8, 0x7966cc, ...)
	F:/GolangWorks/src/github.com/jhump/protoreflect/desc/protoparse/parser.go:154 +0x356
main.main()
	F:/GolangWorks/src/git.dianhun.cn/linbo/xgo/tools/rpc-generator/main.go:86 +0xe3
```
```golang
// @parser.go:1141
func (r *parseResult) generateSourceCodeInfoForEnum(...) {
...
line:1157     // sci.newLoc(evn.number, append(evPath, internal.EnumVal_numberTag))
fix:             sci.newLoc(evn.getNumber(), append(evPath, internal.EnumVal_numberTag))
...
}
```

### PR DESCRIPTION
**Pull request by jhump**
When computing source code info for enum values with a negative numeric value, the `protoparse` package would panic due to a nil de-reference. This fixes that and adds a negative value to a proto to make sure the code and the fix are exercised during tests.

Resolves #139

### CODE REVIEW

File: desc/protoparse/ast.go [hunk 1]
```diff
@@ -785,18 +785,20 @@ type enumValueNode struct {
 	basicCompositeNode
 	name    *identNode
 	options []*optionNode
-	// only one of these two will be set
-	number  *intLiteralNode
-	numberN *negativeIntLiteralNode
+
+	// only one of these two will be set:
+
+	numberP *intLiteralNode         // positive numeric value
```
Comment (jhump) [inline desc/protoparse/ast.go]: So any future changes referencing the field will more likely notice that this is only for positive values -- code either needs explicit check to decide whether to use `numberP` or `numberN` or it should just use the `getNumber()` accessor.

File: desc/protoparse/parser.go [hunk 2]
```diff
@@ -1154,7 +1154,7 @@ func (r *parseResult) generateSourceCodeInfoForEnum(sci *sourceCodeInfo, enum *d
 		evPath := append(path, internal.Enum_valuesTag, int32(j))
 		sci.newLoc(evn, evPath)
 		sci.newLoc(evn.name, append(evPath, internal.EnumVal_nameTag))
-		sci.newLoc(evn.number, append(evPath, internal.EnumVal_numberTag))
+		sci.newLoc(evn.getNumber(), append(evPath, internal.EnumVal_numberTag))
```
Comment (jhump) [inline desc/protoparse/parser.go]: The actual fix, as proposed in #139.

File: internal/testprotos/desc_test_comments.proto [hunk 3]
```diff
@@ -83,6 +82,7 @@ message /* detached message name */ /* request with a capital R */ Request // tr
 		HEY_HO = 7;
 		MAGIKOOPA = 8;
 		KAMEK = 8;
+		SNIFIT = -101;
```
Comment (jhump) [inline internal/testprotos/desc_test_comments.proto]: This negative value revealed the panic when running tests for the protoprint package and confirms that the proposed fix does resolve the error.

File: internal/testprotos/desc_test_oneof.proto [hunk 4]
```diff
@@ -1,6 +1,9 @@
 syntax = "proto3";
+
 package testprotos;
 
+option go_package = "github.com/jhump/protoreflect/internal/testprotos";
```
Comment (jhump) [inline internal/testprotos/desc_test_oneof.proto]: Oops. The `make generate` task was broken because this file was missing a Go package.
